In [1]:
import pandas as pd
import numpy as np

In [2]:
path_to_test_data = "../tests/data/test_data.tsv"
path_to_apple_data = "../data/uniprotkb_organism_id_3750_2024_01_19.tsv"

## Inspect columns

In [3]:
selected_columns = [
    "Entry",
    "Protein names",
    "Gene Names",
    "Organism",
    "Organism (ID)",
    "BRENDA",
    "Gene Ontology IDs",
]
df = pd.read_csv(path_to_apple_data, sep="\t", usecols=selected_columns)
df.head()

/var/folders/tt/plrj7c_x5c769tsqdqgf30w40000gn/T/ipykernel_91666/3717744357.py:10: DtypeWarning: Columns (250) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path_to_apple_data, sep="\t", usecols=selected_columns)

,Entry,Protein names,Gene Names,Organism,Organism (ID),Gene Ontology IDs,BRENDA
0,A0A0E3T3B5,"Aminoaldehyde dehydrogenase 2, peroxisomal (Md...",AMADH2,Malus domestica (Apple) (Pyrus malus),3750,GO:0005777; GO:0019145; GO:0019285; GO:0033737...,1.2.1.19;
1,A0A0E3T552,"Aminoaldehyde dehydrogenase 1, peroxisomal (Md...",AMADH1,Malus domestica (Apple) (Pyrus malus),3750,GO:0005829; GO:0019145; GO:0019285; GO:0033737...,1.2.1.19;
2,P37821,1-aminocyclopropane-1-carboxylate synthase (AC...,ACS-1,Malus domestica (Apple) (Pyrus malus),3750,GO:0009693; GO:0009835; GO:0016491; GO:0016847...,4.4.1.14;
3,Q64FJ6,Alcohol acyl transferase 1 allele RGa (AAT1-RG...,AAT1RGA AAT1,Malus domestica (Apple) (Pyrus malus),3750,GO:0006066; GO:0009723; GO:0009836; GO:0016746,NaN
4,Q84LB2,"(E,E)-alpha-farnesene synthase (MdASF1) (EC 4....",AFS1 AFAR,Malus domestica (Apple) (Pyrus malus),3750,GO:0000287; GO:0005737; GO:0016102; GO:0016740...,4.2.3.46;

In [4]:
for column in selected_columns:
    print(f"{column} NaN: {df[column].isna().any()}")

Entry NaN: False
Protein names NaN: False
Gene Names NaN: True
Organism NaN: False
Organism (ID) NaN: False
BRENDA NaN: True
Gene Ontology IDs NaN: True

## Add NaN row to test data and modify some columns

In [5]:
test_df = df[df["BRENDA"].notna()].head(2)

In [6]:
new_test_row = {
    "Entry": "test_entry",
    "Protein names": "test_name",
    "Gene Names": np.nan,
    "Organism": "Malus domestica",
    "Organism (ID)": 3750,
    "EC number": np.nan,
    "Gene Ontology (GO)": np.nan,
    "Gene Ontology IDs": np.nan,
}

test_df.loc[len(test_df.index)] = new_test_row

In [7]:
test_df.loc[0, "BRENDA"] = "EC.1; 1.1.1.1;"

In [8]:
test_df.loc[0, "Gene Names"] = "Gene1 Gene2 Gene3"

In [9]:
test_df

,Entry,Protein names,Gene Names,Organism,Organism (ID),Gene Ontology IDs,BRENDA
0,A0A0E3T3B5,"Aminoaldehyde dehydrogenase 2, peroxisomal (Md...",Gene1 Gene2 Gene3,Malus domestica (Apple) (Pyrus malus),3750,GO:0005777; GO:0019145; GO:0019285; GO:0033737...,EC.1; 1.1.1.1;
1,A0A0E3T552,"Aminoaldehyde dehydrogenase 1, peroxisomal (Md...",AMADH1,Malus domestica (Apple) (Pyrus malus),3750,GO:0005829; GO:0019145; GO:0019285; GO:0033737...,1.2.1.19;
2,test_entry,test_name,NaN,Malus domestica,3750,NaN,NaN

In [10]:
test_df.to_csv(path_to_test_data, sep="\t")

## Load test data

In [6]:
test_df = pd.read_csv(path_to_test_data, sep="\t", index_col=0, usecols=selected_columns)
test_df

,Protein names,Gene Names,Organism,Proteomes,Virus hosts,Fragment,Gene encoded by,Natural variant,Polymorphism,Active site,...,Temperature dependence,Gene Ontology (GO),Gene Ontology IDs,Topological domain,PubMed ID,DOI ID,Protein families,STRING,UniPathway,BRENDA
Entry,,,,,,,,,,,,,,,,,,,,,
A0A0E3T3B5,"Aminoaldehyde dehydrogenase 2, peroxisomal (Md...",Gene1 Gene2 Gene3,Malus domestica (Apple) (Pyrus malus),NaN,NaN,NaN,NaN,NaN,NaN,"ACT_SITE 260; /note=""Proton acceptor""; /eviden...",...,NaN,peroxisome [GO:0005777]; 1-pyrroline dehydroge...,GO:0005777; GO:0019145; GO:0019285; GO:0033737...,NaN,26296314.0,10.1016/j.febslet.2015.08.005,Aldehyde dehydrogenase family,NaN,UPA00529;,EC.1; 1.2.1.19;
A0A0E3T552,"Aminoaldehyde dehydrogenase 1, peroxisomal (Md...",AMADH1,Malus domestica (Apple) (Pyrus malus),NaN,NaN,NaN,NaN,NaN,NaN,"ACT_SITE 260; /note=""Proton acceptor""; /eviden...",...,NaN,cytosol [GO:0005829]; 1-pyrroline dehydrogenas...,GO:0005829; GO:0019145; GO:0019285; GO:0033737...,NaN,26296314.0,10.1016/j.febslet.2015.08.005,Aldehyde dehydrogenase family,NaN,UPA00529;,1.2.1.19;
test_entry,test_name;,NaN,apple,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN